name: Build and publish NuGet package

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required for Nerdbank.GitVersioning to work
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x


    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore /property:Configuration=Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Install Nerdbank.GitVersioning
      run: dotnet tool install nbgv --tool-path .

    - name: Generate version
      run: nbgv get-version -f json -p .

    - name: Set Environment Variables
      run: nbgv cloud -p . -a 

    # - uses: dotnet/nbgv@master
    #   with:
    #    setAllVars: true

    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
  
      # Display the version stored in the env variable
    - name: Display version
      run: echo $NBGV_NuGetPackageVersion

    - name: Pack      
      run: dotnet pack --no-build -p:PackageVersion=$NBGV_NuGetPackageVersion
    # - name: Publish
    #   run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/$GITHUB_REPOSITORY/index.json --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
