name: Build and publish NuGet package

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Install Nerdbank.GitVersioning
      run: dotnet tool install nbgv --tool-path .

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Generate version
      run: nbgv get-version -v Version > version.txt

    - name: Pack
      run: dotnet pack --no-build -p:PackageVersion=$(cat version.txt)
    # - name: Publish
    #   run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/$GITHUB_REPOSITORY/index.json --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
